### ISSUE TITLE
create JPA Entities

### ISSUE THREAD

**Issue by dm4nk** [dm4nk/Travel-Agency#3]
Build relations in https://www.jhipster.tech/jdl-studio/ or anywhere else and move it to domain package 
After its done, check issue #6 to make some changes

**Comment by LKudraleeva** [comment]
![Снимок экрана (205)](https://user-images.githubusercontent.com/100464458/156369392-f11b1d1f-f2f0-42f1-823a-ce3767859f2d.png)
